apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-mysql
  labels:
    type: local
spec:
  storageClassName: systemfiles
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "./data"